# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "bin/loom", "bin/keys", "bin/loom_anvil",
    "crates/defi-abi", "crates/defi-actors", "crates/defi-entities", "crates/defi-events", "crates/defi-pools", "crates/multicaller", "crates/topology", "crates/types", "crates/utils", "crates/flashbots", "crates/debug-provider"]
default-members = ["bin/loom", "bin/keys", "bin/loom_anvil"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = ""
repository = ""
exclude = [".github/"]

[workspace.dependencies]
loom-actors = { path = "crates/actors" }
loom-actors-macros = { path = "crates/actors-macros" }
loom-utils = { path = "crates/utils" }
loom-multicaller = { path = "crates/multicaller" }
loom-topology = { path = "crates/topology" }
defi-types = { path = "crates/types" }
defi-actors = { path = "crates/defi-actors" }
defi-entities = { path = "crates/defi-entities" }
defi-pools = { path = "crates/defi-pools" }
defi-abi = { path = "crates/defi-abi" }
defi-events = { path = "crates/defi-events" }
flashbots = { path = "crates/flashbots" }
debug-provider = { path = "crates/debug-provider" }


tokio = { version = "1.37.0", features = ["full"] }
eyre = "0.6.12"
env_logger = "0.11.1"
log = "0.4.19"
chrono = "0.4.26"
rayon = "1.8.1"
serde = "^1.0"
serde_json = "^1.0"
lazy_static = "1.4.0"
futures = "0.3.30"
rand = "0.8.5"
num_cpus = "1.16.0"
async-trait = "0.1.80"
hex = "0.4.3"
sha2 = "0.10.7"
aes = "0.8.3"
toml = "^0.8.12"
url = "2.4.1"
reqwest = { version = "0.12.4", features = ["trust-dns", "json"] }
clap = { version = "4.5.4", features = ["derive"] }
k256 = "0.13.3"
strum = "0.26.2"
strum_macros = "0.26.2"




revm = { version = "9.0.0", features = [
    "std",
    "secp256k1",
], default-features = false }
revm-primitives = { version = "3.1.0", features = [
    "std",
], default-features = false }
revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors", rev = "735f67c" }

alloy-chains = "0.1.15"
alloy-primitives = "0.7.2"
alloy-dyn-abi = { version = "0.7.2", features = ["json"] }
alloy-sol-types = { version = "0.7.2", features = ["json"] }
alloy-sol-macro = { version = "0.7.2", features = ["json"] }

alloy-rlp = "0.3.4"
alloy-trie = "0.3.1"
alloy-contract = { path = "../alloy/crates/contract" }
alloy-rpc-client = { path = "../alloy/crates/rpc-client", features = ["ws", "reqwest", "pubsub"] }
alloy-rpc-types = { path = "../alloy/crates/rpc-types" }
alloy-rpc-types-anvil = { path = "../alloy/crates/rpc-types-anvil" }
alloy-rpc-types-trace = { path = "../alloy/crates/rpc-types-trace" }
alloy-rpc-types-engine = { path = "../alloy/crates/rpc-types-engine" }
alloy-genesis = { path = "../alloy/crates/genesis" }
alloy-node-bindings = { path = "../alloy/crates/node-bindings" }
alloy-provider = { path = "../alloy/crates/provider", default-features = false, features = [
    "reqwest", "pubsub", "ws", "ipc"
] }
alloy-eips = { path = "../alloy/crates/eips" }
alloy-signer = { path = "../alloy/crates/signer" }
alloy-signer-wallet = { path = "../alloy/crates/signer-wallet" }
alloy-network = { path = "../alloy/crates/network" }
alloy-consensus = { path = "../alloy/crates/consensus" }
alloy-transport = { path = "../alloy/crates/transport" }
alloy-pubsub = { path = "../alloy/crates/pubsub" }
alloy-transport-ws = { path = "../alloy/crates/transport-ws" }
alloy-transport-http = { path = "../alloy/crates/transport-http" }
alloy-transport-ipc = { path = "../alloy/crates/transport-ipc" }
alloy-json-rpc = { path = "../alloy/crates/json-rpc" }


[patch.crates-io]


