# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "bin/loom", "bin/keys", "bin/loom_anvil", "bin/gasbench", "bin/nodebench",
    "crates/defi-abi", "crates/defi-actors", "crates/defi-entities", "crates/defi-events", "crates/defi-pools", "crates/multicaller", "crates/topology", "crates/types", "crates/utils", "crates/flashbots", "crates/debug-provider", "bin/gasbench", "bin/nodebench", "bin/replayer"]
default-members = ["bin/loom", "bin/keys", "bin/loom_anvil", "bin/gasbench", "bin/nodebench"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.77"
license = "MIT OR Apache-2.0"
homepage = ""
repository = ""
exclude = [".github/"]

[workspace.dependencies]
loom-actors = { path = "crates/actors" }
loom-actors-macros = { path = "crates/actors-macros" }
loom-utils = { path = "crates/utils" }
loom-multicaller = { path = "crates/multicaller" }
loom-topology = { path = "crates/topology" }
defi-types = { path = "crates/types" }
defi-actors = { path = "crates/defi-actors" }
defi-entities = { path = "crates/defi-entities" }
defi-pools = { path = "crates/defi-pools" }
defi-abi = { path = "crates/defi-abi" }
defi-events = { path = "crates/defi-events" }
flashbots = { path = "crates/flashbots" }
debug-provider = { path = "crates/debug-provider" }


tokio = { version = "1.37.0", features = ["full"] }
eyre = "0.6.12"
env_logger = "0.11.1"
log = "0.4.19"
chrono = "0.4.26"
rayon = "1.8.1"
serde = "^1.0"
serde_json = "^1.0"
lazy_static = "1.4.0"
futures = "0.3.30"
rand = "0.8.5"
num_cpus = "1.16.0"
async-trait = "0.1.80"
hex = "0.4.3"
sha2 = "0.10.7"
aes = "0.8.3"
toml = "^0.8.12"
url = "2.4.1"
reqwest = { version = "0.12.4", features = ["trust-dns", "json"] }
clap = { version = "4.5.4", features = ["derive"] }
strum = { version = "0.26.2" }
strum_macros = { version = "0.26.2" }
k256 = "0.13.3"
thiserror = "^1.0.61"
colored = "2.0.4"


alloy-serde = "0.1.3"

alloy = { version = "0.1.3", features = ["full", "serde", "consensus", "node-bindings", "rpc-types-anvil", "rpc-types-trace", "json-rpc", "rpc-types-json"] }

revm = { version = "10.0.0", features = [
    "std",
    "secp256k1",
    "blst",
], default-features = false }
revm-primitives = { version = "5.0.0", features = ["std", ], default-features = false }
revm-inspectors = { git = "https://github.com/paradigmxyz/evm-inspectors", rev = "bc01e05" }


alloy-core = "0.7.6"
alloy-chains = "0.1.15"
alloy-primitives = { version = "0.7.6", features = ["rand"] }
alloy-dyn-abi = { version = "0.7.6", features = ["json"] }
alloy-sol-types = { version = "0.7.6", features = ["json"] }
alloy-sol-macro = { version = "0.7.6", features = ["json"] }

alloy-rlp = "0.3.7"
alloy-trie = "0.4.1"

alloy-contract = "0.1.3"
alloy-consensus = "0.1.3"
alloy-eips = "0.1.3"

alloy-provider = { version = "0.1.3", features = ["reqwest", "pubsub", "ws", "ipc", "debug-api", "anvil-node", "anvil-api"] }
alloy-json-rpc = "0.1.3"
alloy-network = "0.1.3"
alloy-node-bindings = "0.1.3"
alloy-rpc-client = { version = "0.1.3", features = ["pubsub", "ipc", "ws", "reqwest"] }
alloy-rpc-types = "0.1.3"
alloy-rpc-types-eth = "0.1.3"
alloy-rpc-types-anvil = "0.1.3"
alloy-rpc-types-beacon = "0.1.3"
alloy-rpc-types-trace = "0.1.3"
alloy-rpc-types-engine = "0.1.3"
alloy-transport = "0.1.3"
alloy-transport-ipc = "0.1.3"
alloy-transport-ws = "0.1.3"
alloy-transport-http = "0.1.3"
alloy-pubsub = "0.1.3"
alloy-signer = "0.1.3"
alloy-signer-local = "0.1.3"


reth-db = { git = "https://github.com/paradigmxyz/reth", rev = "b93e70c" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", rev = "b93e70c" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", rev = "b93e70c" }
reth-rpc-types = { git = "https://github.com/paradigmxyz/reth", rev = "b93e70c" }
reth-rpc-types-compat = { git = "https://github.com/paradigmxyz/reth", rev = "b93e70c" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", rev = "b93e70c" }


uniswap_v3_math = { git = "https://github.com/dexloom/uniswap-v3-math" }

tower = "0.4.13"

[patch.crates-io]

